server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BackendNetflix
    username: postgres
    password: Onursal77
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false 

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs 